version: '3.8'

services:
  api_users:
    container_name: backend
    build: .
    ports:
      - 3001:3001
    environment: 
      PORT: 3001
    env_file: .env_db
    volumes:
      - ./:/code
      - node_modules:/code/node_modules
    networks: 
      - backend
    depends_on:
      - database

  database_users:
    container_name: database
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db
    env_file: .env_db
    volumes:
      - ./db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./db/.dbshell:/home/mongodb/.dbshell
      - mongodb:/data/db
    networks: 
      - backend

volumes: 
  node_modules:
  mongodb:

networks: 
  backend:
